[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && pnpm --filter=web run build"
watchPatterns = ["apps/web/**", "packages/**"]

[deploy]
startCommand = "pnpm --filter=web run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
