[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && pnpm --filter=api run build"
watchPatterns = ["apps/api/**", "packages/**"]

[deploy]
startCommand = "pnpm --filter=api run db:migrate"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
